/*



*/

#include "eulib.h"
#include "euprobs.h"


/**
 * Problem 1
 * Create a C program that solves the problem below and outputs the answer to
 * standard output:
 * 
 * If we list all the natural numbers below 10 that are multiples of 3 or 5,
 * we get 3, 5, 6 and 9. The sum of these multiples is 23.
 * 
 * Question:
 * Find the sum of all the multiples of 3 or 5 below 1000.
 * 
 * Answer:
 * The sum of all the multiples of 3 or 5 below 1000 is 233168.
 **/
int problem1()
{
    const int MAX = 1000;

    int i3 = 3;
    int i5 = 5;
    int index = 0;
    int count = 0;

    while((i3 < MAX) || (i5 < MAX))
    {
        if(i3 < i5)
        {
            count += i3;
            i3 += 3;
        }
            
        else if(i5 < i3)
        {
            count += i5;
            i5 += 5;
        }
        else i5 += 5;
    }
    
    printf("\nThe sum of all the multiples of 3 or 5 below %d is %d.\n\n", MAX, count);
    fputs("check: 233168\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 2
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 * 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * Question:
 * By considering the terms in the Fibonacci sequence whose values do not
 * exceed four million, find the sum of the even-valued terms.
 * 
 * Answer:
 * The sum of the even-valued terms in the Fibonacci sequence whose values do
 * not exceed four million is 4613732.
 **/
int problem2()
{
    const int MAX = 4000000;
    
    int evenFibs = 0;
    int curFib = 2;
    int preFib = 1;
    int nextFib;
    
    while(curFib < MAX)
    {
        nextFib = curFib + preFib;
        if(curFib %2 == 0)
            evenFibs += curFib;
        preFib = curFib;
        curFib = nextFib;
    }
    
    printf ("\nThe sum of the even-valued terms in the Fibonacci sequence whose\n"
            "values do not exceed %d is %d.\n\n", MAX, evenFibs);
    fputs("check: 4613732\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 3
 * The prime factors of 13195 are 5, 7, 13 and 29.
 * 
 * Question:
 * What is the largest prime factor of the number 600851475143 ?
 * 
 * Answer:
 * The largest prime factor of the number 600851475143 is 6857.
 **/
int problem3()
{
    const long long int MAX = 600851475143;

    long long int index = 1;
    long long int maxPF = MAX;
    long long int minPF = 1;
        
    while(index < maxPF/2)
    {
        if(isFactorL(index, maxPF) && isPrimeL(index))
        {
            minPF = index;
            maxPF /= index;
        }
        else index++;
    }
    printf("\nThe largest prime factor of the number %lld is %lld.\n\n", MAX, maxPF);
    fputs("check: 6857\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 4
 * A palindromic number reads the same both ways. The largest palindrome made
 * from the product of two 2-digit numbers is 9009 = 91 x 99.
 * 
 * Question:
 * Find the largest palindrome made from the product of two 3-digit numbers.
 * 
 * Answer:
 * The largest palindrome made from the product of two 3-digit numbers is
 * 906609 = 993 x 913.
 **/
int problem4()
{
    const int MAXLENGTH = 6;
    const int MAX = 999;

    int i,j,prod,len, ipal, jpal;
    int maxProd = 0;
    char num[MAXLENGTH+1];
    char maxPal[MAXLENGTH+1];
       
    for(i=MAX; i>0; i--)
        for(j=i; j>0; j--)
        {
            prod = i*j;
            
            // len = number of digits in prod, num = string of prod
            len = sprintf(num, "%d", prod);
            
            if(prod>maxProd && isPalindrome(num))
            {
                maxProd = prod;
                ipal = i;
                jpal = j;
                strcpy(maxPal,num);
            }
        }
    printf("\nThe largest palindrome made from the product of two 3-digit \n"
           "numbers is %s = %d x %d.\n\n", maxPal, ipal, jpal);    
    fputs("check: 906609 = 993 x 913\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 5
 * 2520 is the smallest number that can be divided by each of the numbers from
 * 1 to 10 without any remainder.
 * 
 * Question:
 * What is the smallest positive number that is evenly divisible by all of the
 * numbers from 1 to 20?
 * 
 * Answer:
 * The smallest number that can be divided by each of the numbers from 2 to 20
 * without any remainder is: 232792560.
 **/
int problem5()
{
    const int MAX = 20;
    const int MIN = 2;
    
    int i;
    long long int j,k;
    j=1;
    
    for(i=MIN; i<=MAX; i++)
    {
        if(isPrime(i))
        {
            k=i;
            while(k*i<=MAX)
                k*=i;
            j*=k;
        }
    }
    printf("\nThe smallest number that can be divided by each of the numbers from\n"
           "%d to %d without any remainder is: %lld.\n\n", MIN, MAX, j);
    fputs("check: 232792560\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 6
 * The sum of the squares of the first ten natural numbers is,
 * 1^2 + 2^2 + ... + 10^2 = 385
 * 
 * The square of the sum of the first ten natural numbers is,
 * (1 + 2 + ... + 10)^2 = 55^2 = 3025
 * 
 * Hence the difference between the sum of the squares of the first ten natural
 * numbers and the square of the sum is 3025 - 385 = 2640.
 * 
 * Question:
 * Find the difference between the sum of the squares of the first one hundred
 * natural numbers and the square of the sum.
 * 
 * Answer:
 * The difference between the sum of the squares of the first one hundred
 * natural numbers and the square of the sum is 25164150.
 **/
int problem6()
{
    const int MAX = 100;
    
    int i;
    long long int diff;
    
    diff = squareSums(MAX)-sumSquares(MAX);
    printf("\nThe difference between the sum of the squares of the first one\n"
           "hundred natural numbers and the square of the sum is %lld.\n\n", diff);
    fputs("check: 25164150\n\n", stdout);  
    fflush(stdout);
    return 0;
}

/**
 * Problem 7
 * By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see
 * that the 6th prime is 13.
 * 
 * Question:
 * What is the 10,001st prime number?
 * 
 * Answer:
 * The 10001st prime number is 104743.
 **/
int problem7()
{
    const int MAX = 10001;

    int count = 0;
    long long int i = 1;
            
    while(count<MAX)
    {
        i++;
        if(isPrimeL(i))
        {
            count++;
        }
    }
    printf("\nThe %dst prime number is %lld.\n\n", MAX, i);
    fputs("check: 104743\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 8
 * Question:
 * Find the greatest product of five consecutive digits in the 1000-digit number.
 * 
 * 73167176531330624919225119674426574742355349194934
 * 96983520312774506326239578318016984801869478851843
 * 85861560789112949495459501737958331952853208805511
 * 12540698747158523863050715693290963295227443043557
 * 66896648950445244523161731856403098711121722383113
 * 62229893423380308135336276614282806444486645238749
 * 30358907296290491560440772390713810515859307960866
 * 70172427121883998797908792274921901699720888093776
 * 65727333001053367881220235421809751254540594752243
 * 52584907711670556013604839586446706324415722155397
 * 53697817977846174064955149290862569321978468622482
 * 83972241375657056057490261407972968652414535100474
 * 82166370484403199890008895243450658541227588666881
 * 16427171479924442928230863465674813919123162824586
 * 17866458359124566529476545682848912883142607690042
 * 24219022671055626321111109370544217506941658960408
 * 07198403850962455444362981230987879927244284909188
 * 84580156166097919133875499200524063689912560717606
 * 05886116467109405077541002256983155200055935729725
 * 71636269561882670428252483600823257530420752963450
 * 
 * Answer:
 * The greatest product of five consecutive digits in the above 1000-digit
 * number (in problem8.txt), is 40824.
 **/
#define BUFSIZE_8 10000
int problem8()
{

//    const int BUFSIZE = 10000;

    int head, tail, prodfive,max, len;

    //fill buffer with 1000-digit number from input file
    char buffer[BUFSIZE_8] = {0};
    char* infile = "data/problem8.txt";
    fillBufferDigits(buffer, infile);

    //find greatest product
    len = strlen(buffer);
    max = 0;
    head=0; tail = 4;
    while(tail< len-1)
    { 
        if( (prodfive = prodFrom(buffer,head++,tail++)) > max)
            max = prodfive;
    }
    printf("\nThe greatest product of five consecutive digits in "
    "the 1000-digit number, \n\n%s,\n\nis %d.\n\n", buffer,max);

    fputs("check: 40824\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 9
 * A Pythagorean triplet is a set of three natural numbers, a  b  c, for which,
 * a^2 + b^2 = c^2
 * 
 * For example, 3^2 + 4^2 = 9 + 16 = 25 = 5^2.
 * 
 * Question:
 * There exists exactly one Pythagorean triplet for which a + b + c = 1000.
 * Find the product abc.
 * 
 * Answer:
 * There exists exactly one Pythagorean triplet: 200 + 375 + 425 = 1000. The
 * product 200 x 375 x 425 = 31875000.
 **/
int problem9()
{
    const int SUM = 1000;

    int a,b,c;
    
    for(c=2; c<SUM; c++)
        for(b=1; b<c; b++)
            for (a=0; a<b; a++)
                if(checkSum(a,b,c,SUM) && checkSumSquare(a,b,c))
                    printf("\nThere exists exactly one Pythagorean triplet: "
                    "%d + %d + %d = %d.\nThe product %d x %d x %d = %d.\n\n", 
                    a, b, c, SUM, a, b, c, calcProd(a,b,c));

    fputs("check: 31875000\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 10
 * The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17.
 * 
 * Question:
 * Find the sum of all the primes below two million.
 * 
 * Answer:
 * The sum of all the primes below 2000000 is 142913828922.
 **/
int problem10()
{
    const int MAX = 2000000;

    int i;
    long long int sum;

    sum = sumPrimes(MAX);

    printf("The sum of all the primes below %d is %lld.\n", MAX, sum);

    fputs("check: 142913828922\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 11
 * In the 2020 grid below, four numbers along a diagonal line have been marked
 * in (*).
 * 
 * 08 02 22 97 38 15 00 40 00 75 04 05 07 78 52 12 50 77 91 08
 * 49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48 04 56 62 00
 * 81 49 31 73 55 79 14 29 93 71 40 67 53 88 30 03 49 13 36 65
 * 52 70 95 23 04 60 11 42 69 24 68 56 01 32 56 71 37 02 36 91
 * 22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80
 * 24 47 32 60 99 03 45 02 44 75 33 53 78 36 84 20 35 17 12 50
 * 32 98 81 28 64 23 67 10(26)38 40 67 59 54 70 66 18 38 64 70
 * 67 26 20 68 02 62 12 20 95(63)94 39 63 08 40 91 66 49 94 21
 * 24 55 58 05 66 73 99 26 97 17(78)78 96 83 14 88 34 89 63 72
 * 21 36 23 09 75 00 76 44 20 45 35(14)00 61 33 97 34 31 33 95
 * 78 17 53 28 22 75 31 67 15 94 03 80 04 62 16 14 09 53 56 92
 * 16 39 05 42 96 35 31 47 55 58 88 24 00 17 54 24 36 29 85 57
 * 86 56 00 48 35 71 89 07 05 44 44 37 44 60 21 58 51 54 17 58
 * 19 80 81 68 05 94 47 69 28 73 92 13 86 52 17 77 04 89 55 40
 * 04 52 08 83 97 35 99 16 07 97 57 32 16 26 26 79 33 27 98 66
 * 88 36 68 87 57 62 20 72 03 46 33 67 46 55 12 32 63 93 53 69
 * 04 42 16 73 38 25 39 11 24 94 72 18 08 46 29 32 40 62 76 36
 * 20 69 36 41 72 30 23 88 34 62 99 69 82 67 59 85 74 04 36 16
 * 20 73 35 29 78 31 90 01 74 31 49 71 48 86 81 16 23 57 05 54
 * 01 70 54 71 83 51 54 69 16 92 33 48 61 43 52 01 89 19 67 48
 * 
 * The product of these numbers is 26 x 63 x 78 x 14 = 1788696.
 * 
 * Question:
 * What is the greatest product of four adjacent numbers in any direction (up,
 * down, left, right, or diagonally) in the 20x20 grid?
 * 
 * Answer:
 * The greatest product of 4 adjacent numbers in any direction is 70600674.
 **/
int problem11()
{
    const int ROWS = 20;
    const int COLS = 20;
    const int NUM = 4;

    int i, maxprod;
    
    //location of input grid
    char* infile = "data/problem11.txt";

    //allocate a grid on heap
    int **grid = (int**)malloc(ROWS*sizeof(int*));
    for(i=0; i<ROWS; i++)
    {
        grid[i] = (int*)malloc(COLS*sizeof(int));
    }
    
    //fill a grid of size ROWS x COLS with data from input file
    fillGridInts(grid, infile, COLS);
    
    //calculate max prod of NUM consecutive numbers in any direction in a ROW x COL grid
    maxprod = maxProd(grid, ROWS, COLS, NUM);
    
    //print the results
    printf("\nThe greatest product of %d adjacent numbers in any direction\n"
           "(up, down, left, right, or diagonally) in the %dx%d grid:\n", NUM, ROWS, COLS);
    printGridInts(grid, ROWS, COLS);
    printf("\nis %d.\n", maxprod);

    fputs("check: 70600674\n\n", stdout);
    fflush(stdout);

    //deallocate grid from the heap
    for(i=0; i<ROWS; i++)
    {
        free(grid[i]);
    }    
    free(grid);


    return 0;
}

/**
 * Problem 12
 * The sequence of triangle numbers is generated by adding the natural numbers.
 * So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The
 * first ten terms would be:
 * 
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 * 
 * Let us list the factors of the first seven triangle numbers:
 * 
 *  1: 1
 *  3: 1,3
 *  6: 1,2,3,6
 * 10: 1,2,5,10
 * 15: 1,3,5,15
 * 21: 1,3,7,21
 * 28: 1,2,4,7,14,28
 * 
 * We can see that 28 is the first triangle number to have over five divisors.
 * 
 * Question:
 * What is the value of the first triangle number to have over five hundred
 * divisors?
 * 
 * Answer:
 * The value of the first triangle number to have over 500 divisors is 76576500.
 **/
int problem12()
{
    const int TARGET = 500;

    printf("\nThe value of the first triangle number to have over %d "
    "divisors is %d.\n", TARGET, triWithDivs(TARGET) );

    fputs("check: 76576500\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 13
 * Question:
 * Work out the first ten digits of the sum of the following one-hundred
 * 50-digit numbers.(in problem13.txt)
 * 
 * Answer:
 * The first ten digits of the sum of the one-hundred 50-digit numbers (in
 * problem13.txt) is: 5537376230
 **/
#define BUFSIZE_13 5000
int problem13()
{
    const int ROWS = 100;
    const int COLS = 50;
    const int DIGITS = 50;

    int i, j, rc, row, col, cursum, div, mod;
    
    //location of input file
    char* infile = "data/problem13.txt";

    //allocate a grid on heap
    int **grid = (int**)malloc(ROWS*sizeof(int*));
    for(i=0; i<ROWS; i++)
    {
        grid[i] = (int*)malloc(COLS*sizeof(int));
    }
    
    //allocate an array on heap to hold the answer
    int* sum = (int*)malloc(DIGITS*sizeof(int));

    //fill a grid of size ROWS x COLS with data from input file
    fillGridDigits(grid, infile, COLS);

    //print the results
    printf("\nThe first ten digits of the sum of the one-hundred 50-digit "
           "numbers (in problem13.txt)\nis: %d",
           sumDigits(grid, sum, ROWS, COLS, DIGITS));
    printBufDigits(sum, 0, DIGITS);
    fputs("check: 5537376230\n\n", stdout);
    fflush(stdout);
    
    //deallocate grid from the heap
    for(i=0; i<ROWS; i++)
    {
        free(grid[i]);
    }    
    free(grid);
    
    //deallocate sum from heap
    free(sum);


    return 0;
}

/**
 * Problem 14
 * The following iterative sequence is defined for the set of positive
 * integers:
 * 
 *     n -> n/2 (n is even)
 *     n -> 3n + 1 (n is odd)
 * 
 * Using the rule above and starting with 13, we generate the following
 * sequence:
 *     13 -> 40 -> 20 -> 10 -> 5 -> 16 -> 8 -> 4 -> 2 -> 1
 * 
 * It can be seen that this sequence (starting at 13 and finishing at 1)
 * contains 10 terms. Although it has not been proved yet (Collatz Problem), it
 * is thought that all starting numbers finish at 1.
 * 
 * Question:
 * Which starting number, under one million, produces the longest chain?
 * 
 * Answer:
 * The starting number, under 1000000, producing the longest chain is: 837799.
 **/
int problem14()
{
    const int MAX = 1000000;

    int* collatz = (int*)calloc(2*MAX, sizeof(int));

    
    //print the results
    printf("\nThe starting number, under %d, producing the longest chain\nis: %d\n",
           MAX, maxCollatz(collatz, MAX));
    fputs("check: 837799\n\n", stdout);
    fflush(stdout);
    
    free(collatz);    
    return 0;
}

/**
 * Problem 15
 * Starting in the top left corner of a 2x2 grid, there are 6 routes (without
 * backtracking) to the bottom right corner.
 * 
 * Question:
 * How many routes are there through a 2020 grid?
 * 
 * Answer:
 * There are 137846528820 routes through a 20x20 grid.
 **/
int problem15()
{
    const int ROWS = 20;
    const int COLS = 20;
    
    printf("\nThere are %lld routes through a %dx%d grid.\n", choose(ROWS+COLS,ROWS), ROWS, COLS);

    fputs("check: 137846528820\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 16
 * 2^15 = 32768 and the sum of its digits is 3 + 2 + 7 + 6 + 8 = 26.
 * 
 
 0000000000000002
 2 4 8 16 32 64 128 256 512 1024 2048 4096 8192 ....
 
 0-1000000000
 
 10 100 1000
 
 0011 
 
 * Question:
 * What is the sum of the digits of the number 2^1000?
 * 
 * Answer:
 * 
 **/
int problem16()
{
    const int MAX = 1000;
    int i;
    
    //allocate buffers of size MAX
    
    //mul contents of buffer
    
    //add contents of buffer
    
    
    fputs("\nProblem 16 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 17
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem17()
{
    fputs("\nProblem 17 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 18
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem18()
{
    fputs("\nProblem 18 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 19
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem19()
{
    fputs("\nProblem 19 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 20
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem20()
{
    fputs("\nProblem 20 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 21
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem21()
{
    fputs("\nProblem 21 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 22
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem22()
{
    fputs("\nProblem 22 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 23
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem23()
{
    fputs("\nProblem 23 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 24
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem24()
{
    fputs("\nProblem 24 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 25
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem25()
{
    fputs("\nProblem 25 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 26
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem26()
{
    fputs("\nProblem 26 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 27
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem27()
{
    fputs("\nProblem 27 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 28
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem28()
{
    fputs("\nProblem 28 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 29
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem29()
{
    fputs("\nProblem 29 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 30
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem30()
{
    fputs("\nProblem 30 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 31
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem31()
{
    fputs("\nProblem 31 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 32
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem32()
{
    fputs("\nProblem 32 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 33
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem33()
{
    fputs("\nProblem 33 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 34
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem34()
{
    fputs("\nProblem 34 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 35
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem35()
{
    fputs("\nProblem 35 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 36
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem36()
{
    fputs("\nProblem 36 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 37
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem37()
{
    fputs("\nProblem 37 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 38
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem38()
{
    fputs("\nProblem 38 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 39
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem39()
{
    fputs("\nProblem 39 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 40
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem40()
{
    fputs("\nProblem 40 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 41
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem41()
{
    fputs("\nProblem 41 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 42
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem42()
{
    fputs("\nProblem 42 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 43
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem43()
{
    fputs("\nProblem 43 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 44
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem44()
{
    fputs("\nProblem 44 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 45
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem45()
{
    fputs("\nProblem 45 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 46
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem46()
{
    fputs("\nProblem 46 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 47
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem47()
{
    fputs("\nProblem 47 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 48
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem48()
{
    fputs("\nProblem 48 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 49
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem49()
{
    fputs("\nProblem 49 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 50
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem50()
{
    fputs("\nProblem 50 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 51
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem51()
{
    fputs("\nProblem 51 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 52
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem52()
{
    fputs("\nProblem 52 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 53
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem53()
{
    fputs("\nProblem 53 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 54
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem54()
{
    fputs("\nProblem 54 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 55
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem55()
{
    fputs("\nProblem 55 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 56
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem56()
{
    fputs("\nProblem 56 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 57
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem57()
{
    fputs("\nProblem 57 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 58
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem58()
{
    fputs("\nProblem 58 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 59
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem59()
{
    fputs("\nProblem 59 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 60
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem60()
{
    fputs("\nProblem 60 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 61
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem61()
{
    fputs("\nProblem 61 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 62
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem62()
{
    fputs("\nProblem 62 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 63
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem63()
{
    fputs("\nProblem 63 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 64
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem64()
{
    fputs("\nProblem 64 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 65
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem65()
{
    fputs("\nProblem 65 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 66
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem66()
{
    fputs("\nProblem 66 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 67
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem67()
{
    fputs("\nProblem 67 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 68
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem68()
{
    fputs("\nProblem 68 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 69
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem69()
{
    fputs("\nProblem 69 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 70
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem70()
{
    fputs("\nProblem 70 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 71
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem71()
{
    fputs("\nProblem 71 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 72
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem72()
{
    fputs("\nProblem 72 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 73
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem73()
{
    fputs("\nProblem 73 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 74
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem74()
{
    fputs("\nProblem 74 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 75
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem75()
{
    fputs("\nProblem 75 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 76
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem76()
{
    fputs("\nProblem 76 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 77
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem77()
{
    fputs("\nProblem 77 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 78
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem78()
{
    fputs("\nProblem 78 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 79
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem79()
{
    fputs("\nProblem 79 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 80
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem80()
{
    fputs("\nProblem 80 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 81
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem81()
{
    fputs("\nProblem 81 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 82
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem82()
{
    fputs("\nProblem 82 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 83
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem83()
{
    fputs("\nProblem 83 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 84
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem84()
{
    fputs("\nProblem 84 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 85
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem85()
{
    fputs("\nProblem 85 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 86
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem86()
{
    fputs("\nProblem 86 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 87
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem87()
{
    fputs("\nProblem 87 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 88
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem88()
{
    fputs("\nProblem 88 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 89
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem89()
{
    fputs("\nProblem 89 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 90
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem90()
{
    fputs("\nProblem 90 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 91
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem91()
{
    fputs("\nProblem 91 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 92
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem92()
{
    fputs("\nProblem 92 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 93
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem93()
{
    fputs("\nProblem 93 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 94
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem94()
{
    fputs("\nProblem 94 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 95
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem95()
{
    fputs("\nProblem 95 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 96
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem96()
{
    fputs("\nProblem 96 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 97
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem97()
{
    fputs("\nProblem 97 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 98
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem98()
{
    fputs("\nProblem 98 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 99
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem99()
{
    fputs("\nProblem 99 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}

/**
 * Problem 100
 * 
 * 
 * Question:
 * 
 * 
 * Answer:
 * 
 **/
int problem100()
{
    fputs("\nProblem 100 is not yet solved.\n\n", stdout);
    fflush(stdout);
    return 0;
}
